### PR TITLE
removes jruby and ruby 1.9.3 from travis

### PR DESCRIPTION
**Pull request by mejackreed**

### CODE REVIEW

**Comment by jcoyne** [comment]
Why are you removing these?

**Comment by mejackreed** [comment]
@jcoyne https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/ 

Keep it in?

**Comment by jcoyne** [comment]
@mejackreed that article is only for MRI. Jruby is a different implementation entirely.

**Comment by mejackreed** [comment]
Ok... thanks!

**Pull request closed without merging**
